### ISSUE TITLE
Access instance in get_role_id()?

### ISSUE THREAD

**Issue by halfnibble** [allisson/django-rest-framework-role-filters#11]
What if I need access to the instance object in order to return a role_id?

Is there a way to get that for update operations?

**Comment by watsonhaw5566** [comment]
hey, friend . if you use the `request.user` can get user_id and use the  `role_id = User.object.get(id=user_id)` it can get you result .
i think this question can use drf to solve ,don't about role_filter.

**Comment by halfnibble** [comment]
Yes. I was able to figure it out with DRF request. I just added this method to my viewset.
```python3
    def get_role_id(self, request):
        if request.user.is_superuser:
            return CustomRole.Admin
        else:
            return CustomRole.Customer
 ```

**Comment by halfnibble** [comment]
Forgot one thing. In another case, I needed the actual entity _instance_.

For that case, I was able to access it with:
`self.get_instance()` in the `get_role_id()` method.
