### ISSUE TITLE
Using drf generics, mixins

### ISSUE THREAD

**Issue by YashGulati** [allisson/django-rest-framework-role-filters#8]
Let's say I want to use generics.ListCreateAPIView from DRF. How can I do so?

**Comment by imposeren** [comment]
This should be possible if #9 is accepted

**Comment by allisson** [comment]
I just released https://pypi.org/project/djangorestframework-role-filters/0.3.0/ with code from https://github.com/allisson/django-rest-framework-role-filters/pull/9 :+1:
